name: build

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: build-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7.0.0
      - uses: ./.github/actions/setup
      - run: mise run build